name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # JDK 배포판 지정

      - name: Make gradlew executable
        run: chmod +x ./gradlew  # gradlew에 실행 권한 추가

      - name: Build with Gradle
        run: ./gradlew build --no-daemon -x test  # 테스트를 생략하고 빌드

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/AutoMakeCardNews

            # 현재 실행 중인 JAR 프로세스 종료
            pkill -f 'java -jar amcn-0.0.1-SNAPSHOT.jar'

            # JAR 파일 교체
            if [ -f amcn-0.0.1-SNAPSHOT.jar ]; then
              rm amcn-0.0.1-SNAPSHOT.jar
            fi

            # 새로운 JAR 파일을 빌드 디렉토리에서 복사
            scp -o StrictHostKeyChecking=no build/libs/amcn-0.0.1-SNAPSHOT.jar ./

            # 새 JAR 파일로 애플리케이션 실행
            nohup java -jar amcn-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            # Nginx 설치 확인 및 재시작
            if ! command -v nginx &> /dev/null
            then
              echo "Nginx could not be found, installing..."
              sudo apt-get update
              sudo apt-get install -y nginx
              sudo systemctl start nginx
              sudo systemctl enable nginx
            else
              echo "Nginx is already installed, restarting..."
              sudo systemctl restart nginx
            fi
          EOF
