name: Deploy to EC2

on:
  push:
    branches:
      - master  # master 브랜치에 커밋이 발생할 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Java 17로 설정
        distribution: 'temurin'  # 배포판 설정 (temurin 또는 다른 배포판 선택)

    - name: Build with Gradle
      run: ./gradlew build

    - name: Copy JAR file to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        # Add the SSH key to the agent
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem
        eval $(ssh-agent)
        ssh-add ec2_key.pem

        # Copy JAR file to EC2
        scp -o StrictHostKeyChecking=no -i ec2_key.pem build/libs/amcn-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/ubuntu/AutoMakeCardNews/amcn-0.0.1-SNAPSHOT.jar

        # Restart Nginx on EC2
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST 'sudo systemctl restart nginx'

    - name: Clean up
      run: |
        rm -f ec2_key.pem