name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 사용 중인 JDK 버전으로 변경

      - name: Build with Gradle
        run: ./gradlew build --no-daemon -x test  # 테스트를 생략하고 빌드

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/AutoMakeCardNews  # 실제 애플리케이션 디렉토리로 변경
          
            # 현재 실행 중인 JAR 프로세스 종료
            pkill -f 'java -jar build/libs/amcn-0.0.1-SNAPSHOT.jar'
          
            # JAR 파일 교체
            if [ -f amcn-0.0.1-SNAPSHOT.jar ]; then
              rm amcn-0.0.1-SNAPSHOT.jar
            fi
            scp -o StrictHostKeyChecking=no target/amcn-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/AutoMakeCardNews/amcn-0.0.1-SNAPSHOT.jar
          
            # 새 JAR 파일로 애플리케이션 실행
            nohup java -jar build/libs/amcn-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          EOF
